/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:bf99f4dae3ce87873aec1d720903d521:24a06351015a91622530edaac6cafd60:1527f5574ddf4bb74325cca6a4388b6f$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Suika_idle_000 = "suika_idle_000";
		public const string Suika_idle_001 = "suika_idle_001";
		public const string Suika_idle_002 = "suika_idle_002";
		public const string Suika_idle_003 = "suika_idle_003";
		public const string Suika_idle_004 = "suika_idle_004";
		public const string Suika_idle_005 = "suika_idle_005";
		public const string Suika_idle_006 = "suika_idle_006";
		public const string Suika_idle_007 = "suika_idle_007";
		public const string Suika_idle_008 = "suika_idle_008";
		public const string Suika_idle_009 = "suika_idle_009";
		public const string Suika_idle_010 = "suika_idle_010";
		public const string Suika_idle_011 = "suika_idle_011";
		public const string Suika_idle_012 = "suika_idle_012";
		public const string Suika_idle_013 = "suika_idle_013";
		public const string Suika_idle_014 = "suika_idle_014";
		public const string Suika_idle_015 = "suika_idle_015";
		public const string Suika_idle_016 = "suika_idle_016";
		public const string Suika_idle_017 = "suika_idle_017";
	}
}